version: '3'
services:
  app:
    build: .
    environment:
      - MYSQL_HOST=ec2-34-208-78-29.us-west-2.compute.amazonaws.com
      - MYSQL_USER=mysql_user
      - MYSQL_PASSWORD=mysql_password
      - MYSQL_PORT=15306
      - MYSQL_DB_NAME=cell1_keyspace
      - VITESS_READY_QUERIES=no
    ports:
     - "3000:3000"
