version: '3'
services:
  app:
    build: .
    environment:
      - MYSQL_HOST=192.168.86.39
      - MYSQL_USER=mysql_user
      - MYSQL_PASSWORD=mysql_password
      - MYSQL_PORT=15306
      - MYSQL_DB_NAME=test_keyspace
      - VITESS_READY_QUERIES=no
    ports:
     - "3000:3000"
